# Generated by Django 2.1.7 on 2019-04-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Activity',
                'ordering': ['-created'],
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('start_text', models.CharField(max_length=256, verbose_name='Text')),
                ('start_url', models.CharField(max_length=64, verbose_name='Relative Link')),
                ('minimum_player', models.PositiveSmallIntegerField(default=0, verbose_name='Minimum Players')),
                ('minimum_teams', models.PositiveSmallIntegerField(default=0, verbose_name='Minimum Teams')),
                ('minimum_players_per_team', models.PositiveSmallIntegerField(default=0, verbose_name='Minimum Players Per Team')),
            ],
            options={
                'verbose_name': 'Activity Option',
                'ordering': ['-created'],
                'verbose_name_plural': 'Activity Options',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Player',
                'ordering': ['name', '-created'],
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('code', models.SlugField(max_length=16, verbose_name='Code')),
                ('current_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.Activity')),
                ('players', models.ManyToManyField(blank=True, to='rooms.Player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Room',
                'ordering': ['-created'],
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(default='', max_length=64, verbose_name='Team Name')),
                ('players', models.ManyToManyField(blank=True, to='rooms.Player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Team',
                'ordering': ['name', '-created'],
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='teams',
            field=models.ManyToManyField(blank=True, to='rooms.Team'),
        ),
        migrations.AddField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rooms.Room'),
        ),
    ]
