# Generated by Django 2.1.7 on 2019-04-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='rooms.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='games', to='rooms.Team'),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='conditions',
            field=models.ManyToManyField(related_name='condition_groups', to='games.Condition'),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='games.Game'),
        ),
        migrations.AddField(
            model_name='condition',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='games.Game'),
        ),
        migrations.AddField(
            model_name='condition',
            name='parameter_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.Parameter'),
        ),
        migrations.AddField(
            model_name='condition',
            name='parameter_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.Parameter'),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('game', 'key')},
        ),
    ]
