# Generated by Django 2.1.7 on 2019-03-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0003_gamedefinition_first_rule'),
        ('games', '0002_auto_20190329_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('boolean_op', models.PositiveSmallIntegerField(choices=[(0, 'OR'), (1, 'AND')], default=0, verbose_name='Boolean Operation')),
                ('conditions', models.ManyToManyField(related_name='condition_groups', to='games.Condition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('repeats', models.BooleanField(default=False, verbose_name='Repeats')),
                ('trigger_count', models.PositiveSmallIntegerField(default=0, verbose_name='Trigger Count')),
                ('condition_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='games.ConditionGroup')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='games.Game')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gamedefinitions.Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
