# Generated by Django 2.1.7 on 2019-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190405_0109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditionaltransition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conditionaltransition',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='conditionaltransition',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='conditionaltransition',
            name='state_machine',
        ),
        migrations.RemoveField(
            model_name='conditionaltransition',
            name='to_state',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.DeleteModel(
            name='ConditionalTransition',
        ),
    ]
