# Generated by Django 2.1.7 on 2019-04-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Game Definition',
                'ordering': ['-created'],
                'verbose_name_plural': 'Games Definitions',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rule',
                'ordering': ['-created'],
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(max_length=32, verbose_name='Slug')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='StateMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, verbose_name='Slug')),
                ('root_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gamedefinitions.State')),
            ],
            options={
                'verbose_name': 'State Machine',
                'verbose_name_plural': 'State Machines',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=32, verbose_name='Label')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='gamedefinitions.State')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='gamedefinitions.State')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
            },
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='first_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gamedefinitions.Rule'),
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='game_definitions', to='gamedefinitions.Rule'),
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='state_machines',
            field=models.ManyToManyField(blank=True, related_name='game_definitions', to='gamedefinitions.StateMachine'),
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='game_definitions', to='gamedefinitions.State'),
        ),
    ]
