# Generated by Django 2.1.7 on 2019-03-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Game Definition',
                'verbose_name_plural': 'Games Definitions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(max_length=64, verbose_name='Label')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('label', models.SlugField(max_length=32, verbose_name='Label')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('rules', models.ManyToManyField(blank=True, related_name='states', to='gamedefinitions.Rule')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='root_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_definition', to='gamedefinitions.State'),
        ),
    ]
