# Generated by Django 2.1.7 on 2019-03-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=32, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='enter_rules',
            field=models.ManyToManyField(blank=True, related_name='enter_states', to='gamedefinitions.Rule'),
        ),
        migrations.AddField(
            model_name='state',
            name='exit_rules',
            field=models.ManyToManyField(blank=True, related_name='exit_states', to='gamedefinitions.Rule'),
        ),
        migrations.AddField(
            model_name='transition',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='gamedefinitions.State'),
        ),
        migrations.AddField(
            model_name='transition',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='transitions', to='gamedefinitions.Rule'),
        ),
        migrations.AddField(
            model_name='transition',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='gamedefinitions.State'),
        ),
    ]
