# Generated by Django 2.1.7 on 2019-03-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0002_auto_20190329_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefinition',
            name='first_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_definition', to='gamedefinitions.Rule'),
            preserve_default=False,
        ),
    ]
