# Generated by Django 2.1.7 on 2019-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0003_gamedefinition_first_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='label',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='rule',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Slug'),
        ),
    ]
