# Generated by Django 2.1.7 on 2019-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0004_auto_20190331_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='Slug'),
        ),
    ]
