# Generated by Django 2.1.7 on 2019-03-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0005_auto_20190331_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedefinition',
            name='root_state',
        ),
    ]
