# Generated by Django 2.1.7 on 2019-04-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0007_auto_20190405_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='enter_rules',
        ),
        migrations.RemoveField(
            model_name='state',
            name='exit_rules',
        ),
        migrations.RemoveField(
            model_name='state',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='rules',
        ),
    ]
