# Generated by Django 2.1.7 on 2019-04-05 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedefinitions', '0008_auto_20190405_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, verbose_name='Slug')),
                ('root_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gamedefinitions.State')),
            ],
            options={
                'verbose_name': 'State Machine',
                'verbose_name_plural': 'State Machines',
            },
        ),
        migrations.AddField(
            model_name='gamedefinition',
            name='state_machines',
            field=models.ManyToManyField(blank=True, related_name='game_definitions', to='gamedefinitions.StateMachine'),
        ),
    ]
